### ISSUE TITLE
[Bug]  nagram crash 9.7.0

### ISSUE THREAD

**Issue by GreenArchiveForever** [PreviousAlone/Nnngram#28]
### Steps to reproduce

1. [Install Nagram 9.7.0 NoGCM apk](https://t.me/nagram_channel/1624?single)  and do following:
- join a group and block a user
- enable hide message from blocked user
2.  [do a update to Test version, style: change hide phone username to unknown](https://t.me/nagram_channel/1665?single)
3.  view the same group (unblock the user too) and app crashed not even downgrading solve the problem

### Expected behaviour

app should not crashing

### Actual behaviour

app crash even after downgrade

### Smartphone Information

Android 11 (R) Realme UI R Edition
Realme C21Y RMX 3265

### Nnngram Version

9.7.0 + 9.7.6 and the test version

### Version requirement

- [X] I am using latest debug CI version of Nnngram and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs

FATAL EXCEPTION: main
Process: xyz.nextalone.nagram, PID: 18895
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.text.Layout.draw(android.graphics.Canvas)' on a null object reference
	at org.telegram.ui.Cells.ChatMessageCell.drawContent(ChatMessageCell.java:241)
	at org.telegram.ui.Cells.ChatMessageCell.onDraw(ChatMessageCell.java:766)
	at android.view.View.draw(View.java:22464)
	at android.view.View.updateDisplayListIfDirty(View.java:21320)
	at android.view.View.draw(View.java:22175)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4532)
	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:1)
	at org.telegram.ui.ChatActivity$15.drawChild(ChatActivity.java:338)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4293)
	at org.telegram.ui.Components.RecyclerListView.dispatchDraw(RecyclerListView.java:86)
	at org.telegram.ui.ChatActivity$15.dispatchDraw(ChatActivity.java:162)
	at android.view.View.draw(View.java:22467)
	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:1)
	at org.telegram.ui.ChatActivity$15.draw(ChatActivity.java:1140)
	at android.view.View.updateDisplayListIfDirty(View.java:21320)
	at android.view.View.draw(View.java:22175)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4532)
	at org.telegram.ui.ChatActivity$ChatActivityFragmentView.drawChild(ChatActivity.java:578)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4293)
	at org.telegram.ui.Components.SizeNotifierFrameLayout.dispatchDraw(SizeNotifierFrameLayout.java:8)
	at org.telegram.ui.ChatActivity$ChatActivityFragmentView.dispatchDraw(ChatActivity.java:151)
	at android.view.View.draw(View.java:22467)
	at android.view.View.updateDisplayListIfDirty(View.java:21320)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4489)
	at android.view.View.updateDisplayListIfDirty(View.java:21280)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4489)
	at android.view.View.updateDisplayListIfDirty(View.java:21280)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4489)
	at android.view.View.updateDisplayListIfDirty(View.java:21280)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4489)
	at android.view.View.updateDisplayListIfDirty(View.java:21280)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4489)
	at android.view.View.updateDisplayListIfDirty(View.java:21280)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4489)
	at android.view.View.updateDisplayListIfDirty(View.java:21280)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4516)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4489)
	at android.view.View.updateDisplayListIfDirty(View.java:21280)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4181)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3908)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3170)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2023)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8314)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
	at android.view.Choreographer.doCallbacks(Choreographer.java:796)
	at android.view.Choreographer.doFrame(Choreographer.java:731)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7950)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

![Screenshot_20230910-125436](https://github.com/PreviousAlone/Nnngram/assets/136427398/10e39024-bd02-4e09-95b3-b4350509f202)

**Comment by GreenGhostForever** [comment]
hi developer my apologies for posting this here instead in nagram repo

nagram repo have issues disabled
