### ISSUE TITLE
[Bug] 随机出现闪退现象

### ISSUE THREAD

**Issue by CirnoSalt** [PreviousAlone/Nnngram#45]
### Steps to reproduce

随机出现……暂时没找到100%复现的方式，登入两个账号其中一个似乎比另一个出现更频繁（？

### Expected behaviour

正常使用

### Actual behaviour

使用时随机闪退/返回桌面，但系统似乎没有出现崩溃记录。

### Smartphone Information

- Device [Xiaomi13]
- OS [Android 14]
- Version [1.0.8.0]

### Nnngram Version

v10.10.1-9ef68be

### Version requirement

- [X] I am using latest debug CI version of Nnngram and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs

```
--------- beginning of main
04-12 18:13:00.985 13107 13192 E Nnngram : received cancelled chunk after cancelRequests! offset=65536 size=32768 token=60175
04-12 18:13:01.250 13107 13192 E Nnngram : received cancelled chunk after cancelRequests! offset=32768 size=32768 token=60174
04-12 18:13:05.043 13107 13218 E Nnngram : org.telegram.tgnet.TLRPC$TL_channels_getChannelRecommendations@fde4101 got error 400 CHANNEL_INVALID
04-12 18:13:05.222 13107 13218 E Nnngram : org.telegram.tgnet.TLRPC$TL_channels_getChannelRecommendations@80d4b8c got error 400 CHANNEL_INVALID
04-12 18:13:05.223 13107 13209 E Nnngram : FileLoadOperation -1531092872964712362_97.jpg setStream(null)
04-12 18:13:05.778 13107 13218 E Nnngram : org.telegram.tgnet.TLRPC$TL_upload_getFile@8470ba8 got error 400 FILE_REFERENCE_EXPIRED
04-12 18:13:06.796 13107 13192 E Nnngram : org.telegram.messenger.FileLog$IgnoreSentException: trying to write to finished file -1531092872964712365_99.jpg offset 131072 0 reqToken=60229 (state=3)
04-12 18:13:06.796 13107 13192 E Nnngram :      at org.telegram.messenger.FileLoadOperation.processRequestResult(Unknown Source:91)
04-12 18:13:06.796 13107 13192 E Nnngram :      at org.telegram.messenger.FileLoadOperation.lambda$startDownloadRequest$25(Unknown Source:871)
04-12 18:13:06.796 13107 13192 E Nnngram :      at org.telegram.messenger.FileLoadOperation.$r8$lambda$BEwXCmYyj0JvH8_UBPuW0lA7Qe0(SourceFile:0)
04-12 18:13:06.796 13107 13192 E Nnngram :      at org.telegram.messenger.FileLoadOperation$$ExternalSyntheticLambda3.run(SourceFile:0)
04-12 18:13:06.796 13107 13192 E Nnngram :      at org.telegram.tgnet.ConnectionsManager.lambda$sendRequestInternal$4(Unknown Source:2)
04-12 18:13:06.796 13107 13192 E Nnngram :      at org.telegram.tgnet.ConnectionsManager.$r8$lambda$E-t7PEPBKkvojoNznnJ8zemnlAw(SourceFile:0)
04-12 18:13:06.796 13107 13192 E Nnngram :      at org.telegram.tgnet.ConnectionsManager$$ExternalSyntheticLambda15.run(SourceFile:0)
04-12 18:13:06.796 13107 13192 E Nnngram :      at android.os.Handler.handleCallback(Handler.java:958)
04-12 18:13:06.796 13107 13192 E Nnngram :      at android.os.Handler.dispatchMessage(Handler.java:99)
04-12 18:13:06.796 13107 13192 E Nnngram :      at android.os.Looper.loopOnce(Looper.java:224)
04-12 18:13:06.796 13107 13192 E Nnngram :      at android.os.Looper.loop(Looper.java:318)
04-12 18:13:06.796 13107 13192 E Nnngram :      at org.telegram.messenger.DispatchQueue.run(Unknown Source:33)
04-12 18:13:06.798 13107 13192 E Nnngram : org.telegram.messenger.FileLog$IgnoreSentException: trying to write to finished file -1531092872964712365_99.jpg offset 98304 0 reqToken=60228 (state=3)
04-12 18:13:06.798 13107 13192 E Nnngram :      at org.telegram.messenger.FileLoadOperation.processRequestResult(Unknown Source:91)
04-12 18:13:06.798 13107 13192 E Nnngram :      at org.telegram.messenger.FileLoadOperation.lambda$startDownloadRequest$25(Unknown Source:871)
04-12 18:13:06.798 13107 13192 E Nnngram :      at org.telegram.messenger.FileLoadOperation.$r8$lambda$BEwXCmYyj0JvH8_UBPuW0lA7Qe0(SourceFile:0)
04-12 18:13:06.798 13107 13192 E Nnngram :      at org.telegram.messenger.FileLoadOperation$$ExternalSyntheticLambda3.run(SourceFile:0)
04-12 18:13:06.798 13107 13192 E Nnngram :      at org.telegram.tgnet.ConnectionsManager.lambda$sendRequestInternal$4(Unknown Source:2)
04-12 18:13:06.798 13107 13192 E Nnngram :      at org.telegram.tgnet.ConnectionsManager.$r8$lambda$E-t7PEPBKkvojoNznnJ8zemnlAw(SourceFile:0)
04-12 18:13:06.798 13107 13192 E Nnngram :      at org.telegram.tgnet.ConnectionsManager$$ExternalSyntheticLambda15.run(SourceFile:0)
04-12 18:13:06.798 13107 13192 E Nnngram :      at android.os.Handler.handleCallback(Handler.java:958)
04-12 18:13:06.798 13107 13192 E Nnngram :      at android.os.Handler.dispatchMessage(Handler.java:99)
04-12 18:13:06.798 13107 13192 E Nnngram :      at android.os.Looper.loopOnce(Looper.java:224)
04-12 18:13:06.798 13107 13192 E Nnngram :      at android.os.Looper.loop(Looper.java:318)
04-12 18:13:06.798 13107 13192 E Nnngram :      at org.telegram.messenger.DispatchQueue.run(Unknown Source:33)
04-12 18:13:46.927 13107 13209 E Nnngram : FileLoadOperation -1531092872964712362_97.jpg setStream(null)
04-12 18:13:46.982 13107 13218 E Nnngram : java.lang.RuntimeException: can't parse magic cd78e586 in upload_File
04-12 18:13:46.982 13107 13218 E Nnngram :      at org.telegram.tgnet.TLRPC$upload_File.TLdeserialize(Unknown Source:44)
04-12 18:13:46.982 13107 13218 E Nnngram :      at org.telegram.tgnet.TLRPC$TL_upload_getFile.deserializeResponse(Unknown Source:0)
04-12 18:13:46.982 13107 13218 E Nnngram :      at org.telegram.tgnet.ConnectionsManager.lambda$sendRequestInternal$5(Unknown Source:23)
04-12 18:13:46.982 13107 13218 E Nnngram :      at org.telegram.tgnet.ConnectionsManager.$r8$lambda$Ddaf6MxSn5U2Wrearv4nUJkDbXI(SourceFile:0)
04-12 18:13:46.982 13107 13218 E Nnngram :      at org.telegram.tgnet.ConnectionsManager$$ExternalSyntheticLambda14.run(SourceFile:0)
04-12 18:13:46.982 13107 13218 E Nnngram :      at org.telegram.tgnet.ConnectionsManager.onRequestComplete(Unknown Source:57)
04-12 18:13:46.982 13107 13218 E Nnngram : java.lang.RuntimeException: can't parse magic cd78e586 in upload_File
04-12 18:13:46.982 13107 13218 E Nnngram :      at org.telegram.tgnet.TLRPC$upload_File.TLdeserialize(Unknown Source:44)
04-12 18:13:46.982 13107 13218 E Nnngram :      at org.telegram.tgnet.TLRPC$TL_upload_getFile.deserializeResponse(Unknown Source:0)
04-12 18:13:46.982 13107 13218 E Nnngram :      at org.telegram.tgnet.ConnectionsManager.lambda$sendRequestInternal$5(Unknown Source:23)
04-12 18:13:46.982 13107 13218 E Nnngram :      at org.telegram.tgnet.ConnectionsManager.$r8$lambda$Ddaf6MxSn5U2Wrearv4nUJkDbXI(SourceFile:0)
04-12 18:13:46.982 13107 13218 E Nnngram :      at org.telegram.tgnet.ConnectionsManager$$ExternalSyntheticLambda14.run(SourceFile:0)
04-12 18:13:46.982 13107 13218 E Nnngram :      at org.telegram.tgnet.ConnectionsManager.onRequestComplete(Unknown Source:57)
04-12 18:13:46.983 13107 13218 E Nnngram : java.lang.RuntimeException: can't parse magic cd78e586 in upload_File
04-12 18:13:46.983 13107 13218 E Nnngram :      at org.telegram.tgnet.TLRPC$upload_File.TLdeserialize(Unknown Source:44)
04-12 18:13:46.983 13107 13218 E Nnngram :      at org.telegram.tgnet.TLRPC$TL_upload_getFile.deserializeResponse(Unknown Source:0)
04-12 18:13:46.983 13107 13218 E Nnngram :      at org.telegram.tgnet.ConnectionsManager.lambda$sendRequestInternal$5(Unknown Source:23)
04-12 18:13:46.983 13107 13218 E Nnngram :      at org.telegram.tgnet.ConnectionsManager.$r8$lambda$Ddaf6MxSn5U2Wrearv4nUJkDbXI(SourceFile:0)
04-12 18:13:46.983 13107 13218 E Nnngram :      at org.telegram.tgnet.ConnectionsManager$$ExternalSyntheticLambda14.run(SourceFile:0)
04-12 18:13:46.983 13107 13218 E Nnngram :      at org.telegram.tgnet.ConnectionsManager.onRequestComplete(Unknown Source:57)
04-12 18:13:50.000 13107 13192 E Nnngram : received cancelled chunk after cancelRequests! offset=0 size=32768 token=60255
04-12 18:13:50.002 13107 13192 E Nnngram : received cancelled chunk after cancelRequests! offset=0 size=32768 token=60256
04-12 18:13:50.003 13107 13192 E Nnngram : received cancelled chunk after cancelRequests! offset=0 size=32768 token=60259
04-12 18:13:50.003 13107 13192 E Nnngram : received cancelled chunk after cancelRequests! offset=0 size=32768 token=60253
04-12 18:13:50.004 13107 13192 E Nnngram : received cancelled chunk after cancelRequests! offset=0 size=32768 token=60257
04-12 18:13:50.911 13107 13258 E Nnngram : org.telegram.tgnet.TLRPC$TL_channels_getParticipants@fce2df6 got error 400 CHAT_ADMIN_REQUIRED
04-12 18:13:50.916 13107 13258 E Nnngram : org.telegram.tgnet.TLRPC$TL_messages_getScheduledHistory@d230ae7 got error 400 CHAT_ADMIN_REQUIRED
04-12 18:17:17.211 22490 22490 E Nnngram : density = 2.75 display size = 1080 2296 413.755x413.849, screen layout: 268435810, statusbar height: 104, navbar height: 44
04-12 18:17:17.467 22490 22490 E Nnngram : density = 2.75 display size = 1080 2296 413.755x413.849, screen layout: 268435810, statusbar height: 104, navbar height: 44
04-12 18:17:23.479 22490 22624 E Nnngram : org.telegram.tgnet.TLRPC$TL_channels_getParticipants@fc6f921 got error 400 CHAT_ADMIN_REQUIRED
04-12 18:17:23.556 22490 22624 E Nnngram : org.telegram.tgnet.TLRPC$TL_messages_getScheduledHistory@b8bd61c got error 400 CHAT_ADMIN_REQUIRED
04-12 18:17:30.384 22490 22603 E Nnngram : FileLoadOperation 5_6305382199529049713.webm setStream(org.telegram.messenger.AnimatedFileDrawableStream@7d9193f)
04-12 18:17:33.088 22490 22603 E Nnngram : FileLoadOperation -6109348652666436748_120.jpg setStream(null)
04-12 18:17:34.789 22490 22603 E Nnngram : FileLoadOperation -6109348652666436746_121.jpg setStream(null)
04-12 18:17:36.431 22490 22578 E Nnngram : org.telegram.messenger.FileLog$IgnoreSentException: trying to write to finished file -2779848786006091690_97.jpg offset 32768 0 reqToken=6439 (state=3)
04-12 18:17:36.431 22490 22578 E Nnngram :      at org.telegram.messenger.FileLoadOperation.processRequestResult(Unknown Source:91)
04-12 18:17:36.431 22490 22578 E Nnngram :      at org.telegram.messenger.FileLoadOperation.lambda$startDownloadRequest$25(Unknown Source:871)
04-12 18:17:36.431 22490 22578 E Nnngram :      at org.telegram.messenger.FileLoadOperation.$r8$lambda$BEwXCmYyj0JvH8_UBPuW0lA7Qe0(SourceFile:0)
04-12 18:17:36.431 22490 22578 E Nnngram :      at org.telegram.messenger.FileLoadOperation$$ExternalSyntheticLambda3.run(SourceFile:0)
04-12 18:17:36.431 22490 22578 E Nnngram :      at org.telegram.tgnet.ConnectionsManager.lambda$sendRequestInternal$4(Unknown Source:2)
04-12 18:17:36.431 22490 22578 E Nnngram :      at org.telegram.tgnet.ConnectionsManager.$r8$lambda$E-t7PEPBKkvojoNznnJ8zemnlAw(SourceFile:0)
04-12 18:17:36.431 22490 22578 E Nnngram :      at org.telegram.tgnet.ConnectionsManager$$ExternalSyntheticLambda15.run(SourceFile:0)
04-12 18:17:36.431 22490 22578 E Nnngram :      at android.os.Handler.handleCallback(Handler.java:958)
04-12 18:17:36.431 22490 22578 E Nnngram :      at android.os.Handler.dispatchMessage(Handler.java:99)
04-12 18:17:36.431 22490 22578 E Nnngram :      at android.os.Looper.loopOnce(Looper.java:224)
04-12 18:17:36.431 22490 22578 E Nnngram :      at android.os.Looper.loop(Looper.java:318)
04-12 18:17:36.431 22490 22578 E Nnngram :      at org.telegram.messenger.DispatchQueue.run(Unknown Source:33)
04-12 18:17:37.100 22490 22603 E Nnngram : FileLoadOperation -6109348652666436677_121.jpg setStream(null)
04-12 18:17:37.562 22490 22603 E Nnngram : FileLoadOperation -145448294841165847_117.mp4 setStream(org.telegram.messenger.AnimatedFileDrawableStream@e572960)
04-12 18:17:38.002 22490 22578 E Nnngram : org.telegram.messenger.FileLog$IgnoreSentException: trying to write to finished file -145448294841165847_97.jpg offset 32768 0 reqToken=6453 (state=3)
04-12 18:17:38.002 22490 22578 E Nnngram :      at org.telegram.messenger.FileLoadOperation.processRequestResult(Unknown Source:91)
04-12 18:17:38.002 22490 22578 E Nnngram :      at org.telegram.messenger.FileLoadOperation.lambda$startDownloadRequest$25(Unknown Source:871)
04-12 18:17:38.002 22490 22578 E Nnngram :      at org.telegram.messenger.FileLoadOperation.$r8$lambda$BEwXCmYyj0JvH8_UBPuW0lA7Qe0(SourceFile:0)
04-12 18:17:38.002 22490 22578 E Nnngram :      at org.telegram.messenger.FileLoadOperation$$ExternalSyntheticLambda3.run(SourceFile:0)
04-12 18:17:38.002 22490 22578 E Nnngram :      at org.telegram.tgnet.ConnectionsManager.lambda$sendRequestInternal$4(Unknown Source:2)
04-12 18:17:38.002 22490 22578 E Nnngram :      at org.telegram.tgnet.ConnectionsManager.$r8$lambda$E-t7PEPBKkvojoNznnJ8zemnlAw(SourceFile:0)
04-12 18:17:38.002 22490 22578 E Nnngram :      at org.telegram.tgnet.ConnectionsManager$$ExternalSyntheticLambda15.run(SourceFile:0)
04-12 18:17:38.002 22490 22578 E Nnngram :      at android.os.Handler.handleCallback(Handler.java:958)
04-12 18:17:38.002 22490 22578 E Nnngram :      at android.os.Handler.dispatchMessage(Handler.java:99)
04-12 18:17:38.002 22490 22578 E Nnngram :      at android.os.Looper.loopOnce(Looper.java:224)
04-12 18:17:38.002 22490 22578 E Nnngram :      at android.os.Looper.loop(Looper.java:318)
04-12 18:17:38.002 22490 22578 E Nnngram :      at org.telegram.messenger.DispatchQueue.run(Unknown Source:33)
04-12 18:17:40.980 22490 22578 E Nnngram : org.telegram.messenger.FileLog$IgnoreSentException: trying to write to finished file -6300863851440224713_97.jpg offset 32768 0 reqToken=6476 (state=3)
04-12 18:17:40.980 22490 22578 E Nnngram :      at org.telegram.messenger.FileLoadOperation.processRequestResult(Unknown Source:91)
04-12 18:17:40.980 22490 22578 E Nnngram :      at org.telegram.messenger.FileLoadOperation.lambda$startDownloadRequest$25(Unknown Source:871)
04-12 18:17:40.980 22490 22578 E Nnngram :      at org.telegram.messenger.FileLoadOperation.$r8$lambda$BEwXCmYyj0JvH8_UBPuW0lA7Qe0(SourceFile:0)
04-12 18:17:40.980 22490 22578 E Nnngram :      at org.telegram.messenger.FileLoadOperation$$ExternalSyntheticLambda3.run(SourceFile:0)
04-12 18:17:40.980 22490 22578 E Nnngram :      at org.telegram.tgnet.ConnectionsManager.lambda$sendRequestInternal$4(Unknown Source:2)
04-12 18:17:40.980 22490 22578 E Nnngram :      at org.telegram.tgnet.ConnectionsManager.$r8$lambda$E-t7PEPBKkvojoNznnJ8zemnlAw(SourceFile:0)
04-12 18:17:40.980 22490 22578 E Nnngram :      at org.telegram.tgnet.ConnectionsManager$$ExternalSyntheticLambda15.run(SourceFile:0)
04-12 18:17:40.980 22490 22578 E Nnngram :      at android.os.Handler.handleCallback(Handler.java:958)
04-12 18:17:40.980 22490 22578 E Nnngram :      at android.os.Handler.dispatchMessage(Handler.java:99)
04-12 18:17:40.980 22490 22578 E Nnngram :      at android.os.Looper.loopOnce(Looper.java:224)
04-12 18:17:40.980 22490 22578 E Nnngram :      at android.os.Looper.loop(Looper.java:318)
04-12 18:17:40.980 22490 22578 E Nnngram :      at org.telegram.messenger.DispatchQueue.run(Unknown Source:33)
04-12 18:17:41.926 22490 22603 E Nnngram : FileLoadOperation 2_5242512402339089377.webm setStream(org.telegram.messenger.AnimatedFileDrawableStream@16b48c3)
04-12 18:17:41.960 22490 22603 E Nnngram : FileLoadOperation 5_6186051850379200694.webm setStream(org.telegram.messenger.AnimatedFileDrawableStream@59b3423)
04-12 18:17:47.558 22490 22624 E Nnngram : org.telegram.tgnet.TLRPC$TL_channels_getParticipants@a26a0b6 got error 400 CHAT_ADMIN_REQUIRED
04-12 18:17:47.951 22490 22624 E Nnngram : org.telegram.tgnet.TLRPC$TL_messages_getScheduledHistory@f079325 got error 400 CHAT_ADMIN_REQUIRED
（此时出现闪退并跳回桌面）
```

**Comment by CirnoSalt** [comment]
0a78e2d已修复。
